info:
  contact:
    email: support@swagger.io
    name: brewerywiwis
    url: http://www.swagger.io/support
  description: This is a food review system api.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Food Review System API
  version: 0.1.0
paths: {}
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    description: the token is used to authenticate and authorize an user
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
